from fastapi import APIRouter
from app.api.v1.endpoints import (
    login, products, categories, inventory, pos, companies, reports, clients, users, roles, audit, suppliers, purchases, pricelists, sales, admin, branches, logistics, plans, brands, units_of_measure, upload, dashboard, admin_users, system, notifications, notification_admin
)
api_router = APIRouter()
api_router.include_router(login.router, tags=["login"])
api_router.include_router(products.router, prefix="/products", tags=["products"])
api_router.include_router(categories.router, prefix="/categories", tags=["categories"])
api_router.include_router(inventory.router, prefix="/inventory", tags=["inventory"])
api_router.include_router(pos.router, prefix="/pos", tags=["pos"])
api_router.include_router(companies.router, prefix="/companies", tags=["companies"])
api_router.include_router(reports.router, prefix="/reports", tags=["reports"])
api_router.include_router(clients.router, prefix="/clients", tags=["clients"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
api_router.include_router(roles.router, prefix="/roles", tags=["roles"])
api_router.include_router(audit.router, prefix="/audit", tags=["audit"])
api_router.include_router(suppliers.router, prefix="/suppliers", tags=["suppliers"])
api_router.include_router(purchases.router, prefix="/purchases", tags=["purchases"])
api_router.include_router(pricelists.router, prefix="/pricelists", tags=["pricelists"])
api_router.include_router(sales.router, prefix="/sales", tags=["sales"])
api_router.include_router(admin.router, prefix="/admin", tags=["admin"])
api_router.include_router(plans.router, prefix="/plans", tags=["plans"])
api_router.include_router(branches.router, prefix="/branches", tags=["branches"])
api_router.include_router(logistics.router, prefix="/logistics", tags=["logistics"])
api_router.include_router(brands.router, prefix="/brands", tags=["brands"])
api_router.include_router(units_of_measure.router, prefix="/units-of-measure", tags=["units-of-measure"])
api_router.include_router(upload.router, prefix="/upload", tags=["upload"])
api_router.include_router(dashboard.router, prefix="/dashboard", tags=["dashboard"])
api_router.include_router(admin_users.router, prefix="/admin/users", tags=["admin_users"])
api_router.include_router(system.router, prefix="/admin/system", tags=["system"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["notifications"])
api_router.include_router(notification_admin.router, prefix="/admin/notifications", tags=["notification_admin"])
