from fastapi import APIRouter
from app.api.v1.endpoints import (
    login, products, categories, inventory, pos, companies, reports, clients, users, roles, audit, suppliers, purchases, pricelists, sales, admin, branches, logistics
)
api_router = APIRouter()
api_router.include_router(login.router, tags=["login"])
api_router.include_router(products.router, prefix="/products", tags=["products"])
api_router.include_router(categories.router, prefix="/categories", tags=["categories"])
api_router.include_router(inventory.router, prefix="/inventory", tags=["inventory"])
api_router.include_router(pos.router, prefix="/pos", tags=["pos"])
api_router.include_router(companies.router, prefix="/companies", tags=["companies"])
api_router.include_router(reports.router, prefix="/reports", tags=["reports"])
api_router.include_router(clients.router, prefix="/clients", tags=["clients"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
api_router.include_router(roles.router, prefix="/roles", tags=["roles"])
api_router.include_router(audit.router, prefix="/audit", tags=["audit"])
api_router.include_router(suppliers.router, prefix="/suppliers", tags=["suppliers"])
api_router.include_router(purchases.router, prefix="/purchases", tags=["purchases"])
api_router.include_router(pricelists.router, prefix="/pricelists", tags=["pricelists"])
api_router.include_router(sales.router, prefix="/sales", tags=["sales"])
api_router.include_router(admin.router, prefix="/admin", tags=["admin"])
api_router.include_router(branches.router, prefix="/branches", tags=["branches"])
api_router.include_router(logistics.router, prefix="/logistics", tags=["logistics"])
