"""add_button_text_to_plans

Revision ID: 08fa68597343
Revises: 102564761daf
Create Date: 2026-02-19 09:28:22.969918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08fa68597343'
down_revision: Union[str, None] = '102564761daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('button_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'button_text')
    # ### end Alembic commands ###
