"""add_purchase_payment_method

Revision ID: 09ee031ded1a
Revises: 1332c021c31a
Create Date: 2026-02-20 14:02:58.061863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ee031ded1a'
down_revision: Union[str, None] = '1332c021c31a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('payment_method', sa.String(), nullable=False, server_default='CASH'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'payment_method')
    # ### end Alembic commands ###
