"""add app marketplace and notification templates

Revision ID: 102564761daf
Revises: c1f8b0fce2a1
Create Date: 2026-02-17 14:04:04.164994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '102564761daf'
down_revision: Union[str, None] = 'c1f8b0fce2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_definitions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('app_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('app_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('company_app_installs', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('company_app_installs', 'installed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('company_app_installs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_app_installs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('company_app_installs', 'installed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('company_app_installs', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('app_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('app_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('app_definitions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
