"""add_crm_credit_ledger

Revision ID: 1332c021c31a
Revises: 2c3a0673f009
Create Date: 2026-02-20 13:55:31.239270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1332c021c31a'
down_revision: Union[str, None] = '2c3a0673f009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_ledger',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('partner_type', sa.Enum('CLIENT', 'SUPPLIER', name='partnertype'), nullable=False),
    sa.Column('type', sa.Enum('CHARGE', 'PAYMENT', 'REFUND', 'ADJUSTMENT', name='ledgertype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_ledger_partner_id'), 'account_ledger', ['partner_id'], unique=False)
    op.create_index(op.f('ix_account_ledger_reference_id'), 'account_ledger', ['reference_id'], unique=False)
    op.add_column('clients', sa.Column('credit_limit', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('clients', sa.Column('current_balance', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('suppliers', sa.Column('credit_limit', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('suppliers', sa.Column('current_balance', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'current_balance')
    op.drop_column('suppliers', 'credit_limit')
    op.drop_column('clients', 'current_balance')
    op.drop_column('clients', 'credit_limit')
    op.drop_index(op.f('ix_account_ledger_reference_id'), table_name='account_ledger')
    op.drop_index(op.f('ix_account_ledger_partner_id'), table_name='account_ledger')
    op.drop_table('account_ledger')
    # ### end Alembic commands ###
