"""Add currency configuration to Company

Revision ID: 2062ff1fc198
Revises: 30bbde246a87
Create Date: 2026-02-07 10:06:05.019387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2062ff1fc198'
down_revision: Union[str, None] = '30bbde246a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('currency_symbol', sa.String(), nullable=False, server_default='$'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'currency_symbol')
    # ### end Alembic commands ###
