"""add_received_qty_to_purchase_items

Revision ID: 32beb80d9917
Revises: 8dc26717ad26
Create Date: 2026-02-20 07:19:43.435542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32beb80d9917'
down_revision: Union[str, None] = '8dc26717ad26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_items', sa.Column('received_qty', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_items', 'received_qty')
    # ### end Alembic commands ###
