"""add_picking_packing_status

Revision ID: 352f8057008a
Revises: 7c5d4e3f2a1b
Create Date: 2026-02-11 12:20:27.961604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352f8057008a'
down_revision: Union[str, None] = '7c5d4e3f2a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
