"""add brands uom variants enhanced products

Revision ID: 39af1edd2bff
Revises: de1ac885aa3a
Create Date: 2026-02-12 16:27:59.798002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39af1edd2bff'
down_revision: Union[str, None] = 'de1ac885aa3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=False)
    op.create_table('units_of_measure',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_of_measure_name'), 'units_of_measure', ['name'], unique=False)
    op.create_table('product_variants',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('price_extra', sa.Float(), nullable=False),
    sa.Column('cost_extra', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_barcode'), 'product_variants', ['barcode'], unique=False)
    op.create_index(op.f('ix_product_variants_name'), 'product_variants', ['name'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=False)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if 'plans' not in existing_tables:
        op.create_table(
            'plans',
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('code', sa.String(), nullable=False),
            sa.Column('description', sa.String(), nullable=True),
            sa.Column('price', sa.Float(), nullable=False, server_default=sa.text('0.0')),
            sa.Column('currency', sa.String(length=10), nullable=False, server_default=sa.text("'USD'")),
            sa.Column('duration_days', sa.Integer(), nullable=False, server_default=sa.text('30')),
            sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
            sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
            sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
            sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.text('true')),
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False, server_default=sa.text('now()')),
            sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False, server_default=sa.text('now()')),
            sa.Column('created_by_id', sa.UUID(), nullable=True),
            sa.Column('updated_by_id', sa.UUID(), nullable=True),
            sa.Column('company_id', sa.UUID(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('code', name='plans_code_key'),
        )

    if 'system_settings' not in existing_tables:
        op.create_table(
            'system_settings',
            sa.Column('key', sa.String(length=255), nullable=False),
            sa.Column('value', sa.Text(), nullable=True),
            sa.Column('group', sa.String(length=255), nullable=False, server_default=sa.text("'general'")),
            sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.text('false')),
            sa.Column('description', sa.String(), nullable=True),
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False, server_default=sa.text('now()')),
            sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False, server_default=sa.text('now()')),
            sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
            sa.Column('created_by_id', sa.UUID(), nullable=True),
            sa.Column('updated_by_id', sa.UUID(), nullable=True),
            sa.Column('company_id', sa.UUID(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('key', name='system_settings_key_key'),
        )

    op.alter_column('plans', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('plans', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'::character varying"))
    op.alter_column('plans', 'duration_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('plans', 'features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('plans', 'limits',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('plans', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('plans', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    try:
        op.drop_constraint(op.f('plans_code_key'), 'plans', type_='unique')
    except Exception:
        pass
    op.create_index(op.f('ix_plans_code'), 'plans', ['code'], unique=True, if_not_exists=True)
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=False, if_not_exists=True)
    try:
        op.create_foreign_key(None, 'plans', 'companies', ['company_id'], ['id'])
    except Exception:
        pass
    op.add_column('products', sa.Column('internal_reference', sa.String(), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('products', sa.Column('product_type', sa.String(), nullable=False, server_default='STORABLE'))
    op.add_column('products', sa.Column('tax_rate', sa.Float(), nullable=False, server_default='0'))
    op.add_column('products', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('volume', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('sale_ok', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('products', sa.Column('purchase_ok', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('products', sa.Column('brand_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('unit_of_measure_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('purchase_uom_id', sa.UUID(), nullable=True))
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_foreign_key(None, 'products', 'units_of_measure', ['unit_of_measure_id'], ['id'])
    op.create_foreign_key(None, 'products', 'units_of_measure', ['purchase_uom_id'], ['id'])
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'])
    op.alter_column('system_settings', 'group',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('system_settings', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('system_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_settings', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    try:
        op.drop_constraint(op.f('system_settings_key_key'), 'system_settings', type_='unique')
    except Exception:
        pass
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True, if_not_exists=True)
    try:
        op.create_foreign_key(None, 'system_settings', 'companies', ['company_id'], ['id'])
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'system_settings', type_='foreignkey')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.create_unique_constraint(op.f('system_settings_key_key'), 'system_settings', ['key'], postgresql_nulls_not_distinct=False)
    op.alter_column('system_settings', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('system_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_settings', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('system_settings', 'group',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'general'::character varying"))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.alter_column('products', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('products', 'purchase_uom_id')
    op.drop_column('products', 'unit_of_measure_id')
    op.drop_column('products', 'brand_id')
    op.drop_column('products', 'purchase_ok')
    op.drop_column('products', 'sale_ok')
    op.drop_column('products', 'volume')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'tax_rate')
    op.drop_column('products', 'product_type')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'internal_reference')
    op.drop_constraint(None, 'plans', type_='foreignkey')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_index(op.f('ix_plans_code'), table_name='plans')
    op.create_unique_constraint(op.f('plans_code_key'), 'plans', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('plans', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('plans', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('plans', 'limits',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('plans', 'features',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('plans', 'duration_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('30'))
    op.alter_column('plans', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'::character varying"))
    op.alter_column('plans', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_name'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_barcode'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_units_of_measure_name'), table_name='units_of_measure')
    op.drop_table('units_of_measure')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
