"""Add order_date and reference_number to PurchaseOrder

Revision ID: 748070b7032a
Revises: 09ee031ded1a
Create Date: 2026-02-20 15:06:10.031476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '748070b7032a'
down_revision: Union[str, None] = '09ee031ded1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('order_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('purchase_orders', sa.Column('reference_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'reference_number')
    op.drop_column('purchase_orders', 'order_date')
    # ### end Alembic commands ###
