"""add crm fields and client activities table

Revision ID: c9076a6d1ddc
Revises: 748070b7032a
Create Date: 2026-02-23 12:25:37.657428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9076a6d1ddc'
down_revision: Union[str, None] = '748070b7032a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_activities',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CALL', 'MEETING', 'EMAIL', 'NOTE', 'SYSTEM', name='activitytype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_activities_client_id'), 'client_activities', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_activities_user_id'), 'client_activities', ['user_id'], unique=False)
    op.add_column('clients', sa.Column('status', sa.String(), nullable=False, server_default='active'))
    op.add_column('clients', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('clients', sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'last_interaction_at')
    op.drop_column('clients', 'tags')
    op.drop_column('clients', 'status')
    op.drop_index(op.f('ix_client_activities_user_id'), table_name='client_activities')
    op.drop_index(op.f('ix_client_activities_client_id'), table_name='client_activities')
    op.drop_table('client_activities')
    # ### end Alembic commands ###
