"""add_delivery_fields_to_sales

Revision ID: d1b7ed5945b9
Revises: 32beb80d9917
Create Date: 2026-02-20 09:35:04.280844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b7ed5945b9'
down_revision: Union[str, None] = '32beb80d9917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sales', sa.Column('delivery_notes', sa.String(), nullable=True))
    op.add_column('sales', sa.Column('delivery_evidence_url', sa.String(), nullable=True))
    op.add_column('sales', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'completed_at')
    op.drop_column('sales', 'delivery_evidence_url')
    op.drop_column('sales', 'delivery_notes')
    op.drop_column('sales', 'delivered_at')
    # ### end Alembic commands ###
