"""add_missing_sale_status_enums

Revision ID: de1ac885aa3a
Revises: ef22b382ba8a
Create Date: 2026-02-12 07:24:54.628237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de1ac885aa3a'
down_revision: Union[str, None] = 'ef22b382ba8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Safe add using DO block
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid WHERE t.typname = 'salestatus' AND e.enumlabel = 'PICKING') THEN
            ALTER TYPE salestatus ADD VALUE 'PICKING';
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid WHERE t.typname = 'salestatus' AND e.enumlabel = 'PACKING') THEN
            ALTER TYPE salestatus ADD VALUE 'PACKING';
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid WHERE t.typname = 'salestatus' AND e.enumlabel = 'DISPATCHED') THEN
            ALTER TYPE salestatus ADD VALUE 'DISPATCHED';
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid WHERE t.typname = 'salestatus' AND e.enumlabel = 'DELIVERED') THEN
            ALTER TYPE salestatus ADD VALUE 'DELIVERED';
        END IF;
    END$$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
