"""add variant_id to purchase_order_items

Revision ID: df210f2698ed
Revises: 08fa68597343
Create Date: 2026-02-19 15:02:27.344758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df210f2698ed'
down_revision: Union[str, None] = '08fa68597343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_items', sa.Column('variant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'purchase_order_items', 'product_variants', ['variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_order_items', type_='foreignkey')
    op.drop_column('purchase_order_items', 'variant_id')
    # ### end Alembic commands ###
