"""add_price_lists

Revision ID: ee06c75add9f
Revises: f3ba2a847c01
Create Date: 2026-02-10 10:19:36.564823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee06c75add9f'
down_revision: Union[str, None] = 'f3ba2a847c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('SALE', 'PURCHASE', name='pricelisttype'), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_lists_name'), 'price_lists', ['name'], unique=False)
    op.create_table('pricelist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pricelist_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('min_quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['pricelist_id'], ['price_lists.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricelist_items_pricelist_id'), 'pricelist_items', ['pricelist_id'], unique=False)
    op.create_index(op.f('ix_pricelist_items_product_id'), 'pricelist_items', ['product_id'], unique=False)
    op.add_column('clients', sa.Column('price_list_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'clients', 'price_lists', ['price_list_id'], ['id'])
    op.add_column('suppliers', sa.Column('price_list_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'suppliers', 'price_lists', ['price_list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'price_list_id')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'price_list_id')
    op.drop_index(op.f('ix_pricelist_items_product_id'), table_name='pricelist_items')
    op.drop_index(op.f('ix_pricelist_items_pricelist_id'), table_name='pricelist_items')
    op.drop_table('pricelist_items')
    op.drop_index(op.f('ix_price_lists_name'), table_name='price_lists')
    op.drop_table('price_lists')
    # ### end Alembic commands ###
