"""add_logistics_models

Revision ID: ef22b382ba8a
Revises: 352f8057008a
Create Date: 2026-02-11 13:50:56.330654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef22b382ba8a'
down_revision: Union[str, None] = '352f8057008a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_types',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('max_weight', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_types_name'), 'package_types', ['name'], unique=True)
    op.create_table('sale_packages',
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('package_type_id', sa.UUID(), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('shipping_label_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['package_type_id'], ['package_types.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_packages_sale_id'), 'sale_packages', ['sale_id'], unique=False)
    op.create_table('sale_package_items',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('sale_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['sale_packages.id'], ),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_package_items_package_id'), 'sale_package_items', ['package_id'], unique=False)
    
    # 1. Add as nullable
    op.add_column('sale_items', sa.Column('quantity_picked', sa.Float(), nullable=True))
    # 2. Update existing rows
    op.execute("UPDATE sale_items SET quantity_picked = 0.0")
    # 3. Alter to non-nullable
    op.alter_column('sale_items', 'quantity_picked', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_items', 'quantity_picked')
    op.drop_index(op.f('ix_sale_package_items_package_id'), table_name='sale_package_items')
    op.drop_table('sale_package_items')
    op.drop_index(op.f('ix_sale_packages_sale_id'), table_name='sale_packages')
    op.drop_table('sale_packages')
    op.drop_index(op.f('ix_package_types_name'), table_name='package_types')
    op.drop_table('package_types')
    # ### end Alembic commands ###
