from typing import Any, Dict, List


APP_REGISTRY: List[Dict[str, Any]] = [
    {
        "slug": "eleganthome",
        "name": "ElegantHome",
        "description": "Conecta ElegantHome con Lumefy para sincronizar productos, inventario y órdenes.",
        "category": "Integraciones",
        "version": "1.0.0",
        "icon": "cloud-download",
        "requested_scopes": [
            "products:read",
            "products:write",
            "inventory:read",
            "inventory:write",
            "orders:read",
            "orders:write",
            "customers:read",
            "customers:write",
        ],
        "capabilities": [
            "catalog_sync",
            "inventory_sync",
            "order_import",
            "order_export",
            "webhooks",
        ],
        "pricing_model": "included",
        "monthly_price": 0,
        "config_schema": {
            "type": "object",
            "properties": {
                "default_sync_mode": {
                    "type": "string",
                    "title": "Modo de sincronización por defecto",
                    "enum": ["manual", "automatic"],
                },
                "default_branch_id": {
                    "type": "string",
                    "title": "Sucursal por defecto para órdenes",
                },
                "default_warehouse_id": {
                    "type": "string",
                    "title": "Bodega por defecto para órdenes",
                },
                "default_payment_method": {
                    "type": "integer",
                    "title": "Método de pago ElegantHome",
                },
            },
        },
        "default_config": {
            "default_sync_mode": "manual",
            "connection_defaults": {
                "base_url": "https://panel.tuhogaronline.com",
                "auth_type": "api_key",
                "api_key_header": "X-Api-Key",
                "currency": "COP",
                "endpoints": {
                    "products": {
                        "path": "/api/external/products",
                        "data_path": "data",
                        "pagination": {
                            "enabled": True,
                            "type": "page",
                            "page_param": "page",
                            "per_page_param": "per_page",
                            "per_page": 50,
                            "start_page": 1,
                            "max_pages": 1000,
                            "last_page_path": "pagination.pages",
                            "total_path": "pagination.total",
                        },
                    },
                    "inventory": {
                        "path": "/api/external/inventory",
                        "data_path": "data",
                        "batch": {
                            "enabled": True,
                            "query_param": "skus",
                            "size": 100,
                        },
                    },
                    "orders": {
                        "path": "/api/external/orders",
                        "data_path": "data",
                        "pagination": {
                            "enabled": True,
                            "type": "page",
                            "page_param": "page",
                            "per_page_param": "per_page",
                            "per_page": 20,
                            "start_page": 1,
                            "max_pages": 1000,
                            "last_page_path": "pagination.pages",
                            "total_path": "pagination.total",
                        },
                        "detail_path": "/api/external/orders/{id}",
                        "detail_data_path": "data",
                        "id_path": "id",
                    },
                },
                "catalog_transform": {
                    "mode": "flat_variants",
                    "parent_path": "item",
                    "variant_external_id_path": "id",
                    "variant_sku_path": "sku",
                    "variant_name_paths": ["color", "size"],
                    "variant_attribute_paths": ["color", "size"],
                },
                "collections": {
                    "variants_path": "variants[]",
                },
                "field_map": {
                    "product.external_id": "id",
                    "product.name": "product_name",
                    "product.sku": "sku",
                    "product.price": "price",
                    "variant.external_id": "variants[].id",
                    "variant.sku": "variants[].sku",
                    "variant.name": "variants[].name",
                    "variant.price": "variants[].price",
                    "variant.stock": "variants[].stock",
                    "variant.attributes": "variants[].attributes",
                    "inventory.external_id": "sku",
                    "inventory.sku": "sku",
                    "inventory.quantity": "stock",
                },
                "order_mapping": {
                    "id": "id",
                    "number": "invoice",
                    "tracking": "track",
                    "status": "state",
                    "total": "total",
                    "created_at": "created",
                    "customer_name": "client_name",
                    "items": "items",
                    "item_sku": "sku",
                    "item_quantity": "qty",
                    "item_unit_price": "unit_price",
                    "item_total": "line_total",
                },
            },
        },
        "setup_url": "/apps/installed/eleganthome/connections",
    },
    {
        "slug": "ecommerce",
        "name": "Ecommerce",
        "description": "Tienda online nativa conectada con catalogo, inventario, pedidos y clientes.",
        "category": "Canales de venta",
        "version": "1.0.0",
        "icon": "shop",
        "requested_scopes": ["products:read", "inventory:read", "sales:create", "clients:write"],
        "capabilities": ["storefront", "checkout", "custom_domains", "catalog_sync"],
        "pricing_model": "included",
        "monthly_price": 0,
        "config_schema": {
            "type": "object",
            "properties": {
                "allow_custom_domains": {"type": "boolean", "title": "Permitir dominios propios"},
                "default_currency": {"type": "string", "title": "Moneda por defecto"},
            },
        },
        "default_config": {
            "allow_custom_domains": True,
            "default_currency": "USD",
        },
        "setup_url": "/apps/ecommerce",
    },
    {
        "slug": "pos_module",
        "name": "Punto de Venta (POS)",
        "description": "Sistema de cobro rapido para mostrador, optimizado para flujo de caja y ticket.",
        "category": "Ventas",
        "version": "1.0.0",
        "icon": "calculator",
        "requested_scopes": ["sales:create", "inventory:write", "products:read"],
        "capabilities": ["pos_screen", "receipt_printing", "inventory_sync"],
        "pricing_model": "included",
        "monthly_price": 0,
        "config_schema": {
            "type": "object",
            "properties": {
                "thermal_printer_paper": {
                    "type": "string",
                    "title": "Tamano de Papel",
                    "enum": ["80mm", "58mm"],
                },
                "allow_negative_stock": {"type": "boolean", "title": "Permitir ventas sin stock"},
                "default_cash_drawer": {"type": "string", "title": "Caja Registradora Predeterminada"},
                "require_manager_for_void": {"type": "boolean", "title": "Requerir clave para anular ventas"},
                "show_sessions_manager": {"type": "boolean", "title": "Mostrar gestor de cajas"},
                "session_visibility_scope": {
                    "type": "string",
                    "title": "Visibilidad de cajas",
                    "enum": ["own", "branch", "company"],
                },
                "allow_multiple_open_sessions_per_branch": {
                    "type": "boolean",
                    "title": "Permitir varias cajas abiertas por sucursal (usuarios distintos)",
                },
                "allow_enter_other_user_session": {
                    "type": "boolean",
                    "title": "Permitir entrar a caja de otro usuario",
                },
            },
        },
        "default_config": {
            "thermal_printer_paper": "80mm",
            "allow_negative_stock": False,
            "default_cash_drawer": "Main Register",
            "require_manager_for_void": True,
            "show_sessions_manager": True,
            "session_visibility_scope": "branch",
            "allow_multiple_open_sessions_per_branch": True,
            "allow_enter_other_user_session": False,
        },
        "setup_url": "/apps/installed/pos_module",
    },
]
